"""Initial migration after reset

Revision ID: 3dc84708b299
Revises: 
Create Date: 2025-04-04 08:37:29.615908

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3dc84708b299'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_defect')
    with op.batch_alter_table('defect', schema=None) as batch_op:
        batch_op.alter_column('defect_mode',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('defect_rate',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)
        batch_op.alter_column('image_path',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_defect_defect_name'), ['defect_name'], unique=True)

    with op.batch_alter_table('pdf_file', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_pdf_file_file_name', ['file_name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pdf_file', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('defect', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_defect_defect_name'))
        batch_op.alter_column('image_path',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)
        batch_op.alter_column('defect_rate',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('defect_mode',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)

    op.create_table('_alembic_tmp_defect',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('defect_name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('defect_mode', sa.VARCHAR(length=100), nullable=False),
    sa.Column('description', sa.VARCHAR(length=500), nullable=False),
    sa.Column('image_path', sa.VARCHAR(length=200), nullable=False),
    sa.Column('defect_rate', sa.VARCHAR(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('defect_name')
    )
    # ### end Alembic commands ###
