"""Latest changes

Revision ID: 5b8cd956a995
Revises: b5449e639cb3
Create Date: 2025-04-23 08:24:45.347111

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b8cd956a995'
down_revision = 'b5449e639cb3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('defect', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=100), nullable=False))
        batch_op.drop_index('ix_defect_defect_name')
        batch_op.drop_column('defect_name')
        batch_op.drop_column('description')

    with op.batch_alter_table('defect_mode', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mode', sa.String(length=100), nullable=False))
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.Text(),
               nullable=True)
        batch_op.alter_column('image_filename',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=255),
               nullable=True)
        batch_op.drop_column('image_path')
        batch_op.drop_column('mode_name')

    with op.batch_alter_table('pdf_file', schema=None) as batch_op:
        batch_op.add_column(sa.Column('filename', sa.String(length=255), nullable=False))
        batch_op.drop_constraint('uq_pdf_file_file_name', type_='unique')
        batch_op.drop_column('file_path')
        batch_op.drop_column('file_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pdf_file', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_name', sa.VARCHAR(length=200), nullable=False))
        batch_op.add_column(sa.Column('file_path', sa.VARCHAR(length=300), nullable=False))
        batch_op.create_unique_constraint('uq_pdf_file_file_name', ['file_name'])
        batch_op.drop_column('filename')

    with op.batch_alter_table('defect_mode', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mode_name', sa.VARCHAR(length=100), nullable=False))
        batch_op.add_column(sa.Column('image_path', sa.VARCHAR(length=300), nullable=False))
        batch_op.alter_column('image_filename',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=200),
               nullable=False)
        batch_op.alter_column('description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=500),
               nullable=False)
        batch_op.drop_column('mode')

    with op.batch_alter_table('defect', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.VARCHAR(length=500), nullable=True))
        batch_op.add_column(sa.Column('defect_name', sa.VARCHAR(length=100), nullable=False))
        batch_op.create_index('ix_defect_defect_name', ['defect_name'], unique=False)
        batch_op.drop_column('name')

    # ### end Alembic commands ###
