"""Refactor models for multiple defect modes

Revision ID: a69e049cfdbe
Revises: 3dc84708b299
Create Date: 2025-04-09 10:41:28.891996

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a69e049cfdbe'
down_revision = '3dc84708b299'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('defect_mode',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('defect_id', sa.Integer(), nullable=False),
    sa.Column('mode_name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('image_filename', sa.String(length=200), nullable=False),
    sa.Column('image_path', sa.String(length=300), nullable=False),
    sa.ForeignKeyConstraint(['defect_id'], ['defect.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('image_filename')
    )
    with op.batch_alter_table('defect', schema=None) as batch_op:
        batch_op.alter_column('defect_rate',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.drop_index('ix_defect_defect_name')
        batch_op.create_index(batch_op.f('ix_defect_defect_name'), ['defect_name'], unique=False)
        batch_op.drop_column('image_path')
        batch_op.drop_column('description')
        batch_op.drop_column('defect_mode')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('defect', schema=None) as batch_op:
        batch_op.add_column(sa.Column('defect_mode', sa.VARCHAR(length=100), nullable=False))
        batch_op.add_column(sa.Column('description', sa.VARCHAR(length=500), nullable=False))
        batch_op.add_column(sa.Column('image_path', sa.VARCHAR(length=200), nullable=False))
        batch_op.drop_index(batch_op.f('ix_defect_defect_name'))
        batch_op.create_index('ix_defect_defect_name', ['defect_name'], unique=1)
        batch_op.alter_column('defect_rate',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)

    op.drop_table('defect_mode')
    # ### end Alembic commands ###
